한상범/flask_study/pybo/models.py
from pybo import db

class Question(db.Model):
    id = db.Column(db.Integer, primary_key=True) # 기본키

    subject = db.Column(db.String(200), nullable=False)
    content = db.Column(db.Text(), nullable=False)
    create_date = db.Column(db.DateTime(), nullable=False)

class Answer(db.Model):
    id = db.Column(db.Integer, primary_key=True)

    question_id = db.Column(db.Integer, db.ForeignKey('question.id', ondelete='CASCADE'))
    question = db.relationship('Question', backref=db.backref('answer_set'))

    # question = db.relationship('Question', backref=db.backref('answer_set', cascade='all, delete-orphan'))

    content = db.Column(db.Text(), nullable=False)
    create_date = db.Column(db.DateTime(), nullable=False)

class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(), nullable=False, unique=True)
    password = db.Column(db.String(), nullable=False)
    email = db.Column(db.String(), nullable=False, unique=True)

한상범/flask_study/pybo/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, PasswordField, EmailField
from wtforms.validators import DataRequired, Length, EqualTo, Email

class QuestionForm(FlaskForm):
    subject = StringField('제목', validators=[DataRequired()])
    content = TextAreaField('내용', validators=[DataRequired()])

class AnswerForm(FlaskForm):
    content = TextAreaField('내용', validators=[DataRequired('내용은 필수입력 항목입니다.')])

class UserCreateForm(FlaskForm):
    email = EmailField('이메일', validators=[DataRequired(), Email()])
    username = StringField('사용자이름', validators=[DataRequired(), Length(min=3, max=25)])
    password1 = PasswordField('비밀번호', validators=[DataRequired(),\
        EqualTo('password2', '비밀번호가 일치하지 않습니다')])
    password2 = PasswordField('비밀번호확인', validators=[DataRequired()])

class UserLoginForm(FlaskForm):
    username = StringField('사용자이름', validators=[DataRequired(), Length(min=3, max=25)])
    password = PasswordField('비밀번호', validators=[DataRequired()])

한상범/flask_study/pybo/__init__.py
from flask import Flask
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy

import config

db = SQLAlchemy() # 추가
migrate = Migrate() # 추가

def create_app():
    app = Flask(__name__)

    # 추가
    # config.py 파일에 작성한 항목을 읽기 위함
    app.config.from_object(config)

    #ORM 추가
    # db와 migrate 객체를 app에 등록
    db.init_app(app)
    migrate.init_app(app, db)
    from . import models # 작성한 모델을 migrate 기능이 인식하려면 inmport가 필요

    from .views import main_views, question_views, answer_views, auth_views
    app.register_blueprint(main_views.bp)
    app.register_blueprint(question_views.bp)
    app.register_blueprint(answer_views.bp)
    app.register_blueprint(auth_views.bp)

    return app

한상범/flask_study/pybo/views/answer_views.py
from datetime import datetime
from flask import Blueprint, url_for, request, render_template
from werkzeug.utils import redirect

from .. import db
from pybo.forms import AnswerForm
from pybo.models import Question, Answer

bp = Blueprint('answer', __name__, url_prefix='/answer')

@bp.route('/create/<int:question_id>', methods=('POST',))
def create(question_id):
    form = AnswerForm()
    question = Question.query.get_or_404(question_id)
    if form.validate_on_submit():
        question = Question.query.get_or_404(question_id) # 매개변수로 전달 받은 id의 질문
        content = request.form['content'] # POST 방식으로 전송된 데이터 항목 중 name 속성이 content인 값
        answer = Answer(question = question, content=content, create_date=datetime.now()) # 답변을 하나 만듬
        question.answer_set.append(answer) # 답변에 답변을 더함
        db.session.commit()
        return redirect(url_for('question.detail', question_id=question_id))

    return render_template('question/question_detail.html', question=question, form=form)

한상범/flask_study/pybo/views/auth_views.py
from flask import Blueprint, url_for, render_template, flash, request, session, g
from werkzeug.security import generate_password_hash, check_password_hash
from werkzeug.utils import redirect

from pybo import db
from pybo.forms import UserCreateForm, UserLoginForm
from pybo.models import User

bp = Blueprint('auth', __name__, url_prefix='/auth')


@bp.route('/signup/', methods=('GET', 'POST'))
def signup(): 
    form = UserCreateForm()
    if request.method == 'POST' and form.validate_on_submit():

        # username으로 데이터를 조회해서
        user = User.query.filter_by(username=form.username.data).first()

        # 이미 등록된 사용자인지 확인
        if not user:
            user = User(username=form.username.data,
                        # 암호화 저장
                        password=generate_password_hash(form.password1.data),
                        email=form.email.data)
            db.session.add(user)
            db.session.commit()
            return redirect(url_for('main.index'))
        else:
            flash('이미 존재하는 사용자입니다.') # 이미 등록된 경우
    return render_template('auth/signup.html', form=form)    


@bp.route('/login/', methods=('GET', 'POST'))
def login():
    form = UserLoginForm()
    if request.method == 'POST' and form.validate_on_submit():
        error = None
        user = User.query.filter_by(username=form.username.data).first()
        if not user:
            error = "존재하지 않는 사용자입니다."

        # password와 check_password_hash 함수를 사용하여 입력 비밀번호와 DB 비밀번호 비교
        elif not check_password_hash(user.password, form.password.data):
            error = "비밀번호가 올바르지 않습니다."
        if error is None:

            # 플라스크 세션에 사용자 정보를 저장
            session.clear()
            session['user_id'] = user.id # 세션 키에 user_id 문자열을 저장하고 db id를 저장
            return redirect(url_for('main.index'))
        flash(error)
    return render_template('auth/login.html', form=form)

@bp.before_app_request
def load_logged_in_user():
    user_id = session.get('user_id')
    if user_id is None:
        g.user = None
    else:
        g.user = User.query.get(user_id)

@bp.route('/logout/')
def logout():
    session.clear()
    return redirect(url_for('main.index'))        

한상범/flask_study/pybo/views/main_views.py
from flask import Blueprint, url_for
from werkzeug.utils import redirect

'''
인수 1 블루프린트의 '별칭'으로 url_for 함수에서 사용된다.
인수 2 모듈 명 main_views가 전달
인수 3 라우팅 함수의 애너테이션 URL 암페 기본으로 붙일 URL

-> 원래 hello_pybo는 '/'이니 localhost:5000/으로 입력하는데 
url_p가 '/main'이었다면 localhost:5000[/main]/이다. = 애너테이션 URL의 앞에 /main을 붙여야한다.
'''

bp = Blueprint('main', __name__, url_prefix='/')

@bp.route('/hello')
def hello_pybo():
    return 'Hello, Pybo!'

@bp.route('/')
def index():
    return redirect(url_for('question._list'))

한상범/flask_study/pybo/views/question_views.py
from datetime import datetime

from flask import Blueprint, render_template, request, url_for
from werkzeug.utils import redirect

from .. import db
from pybo.models import Question
from pybo.forms import QuestionForm, AnswerForm

'''
인수 1 블루프린트의 '별칭'으로 url_for 함수에서 사용된다.
인수 2 모듈 명 main_views가 전달
인수 3 라우팅 함수의 애너테이션 URL 암페 기본으로 붙일 URL

-> 원래 hello_pybo는 '/'이니 localhost:5000/으로 입력하는데 
url_p가 '/main'이었다면 localhost:5000[/main]/이다. = 애너테이션 URL의 앞에 /main을 붙여야한다.
'''

bp = Blueprint('question', __name__, url_prefix='/question')

@bp.route('/list/')
def _list():
    question_list = Question.query.order_by(Question.create_date.desc())
    return render_template('question/question_list.html', question_list = question_list)

@bp.route('/create/', methods = ('GET', 'POST'))
def create():
    form = QuestionForm()
    if request.method == 'POST' and form.validate_on_submit():
        question = Question(subject=form.subject.data, content=form.content.data, create_date=datetime.now())
        db.session.add(question)
        db.session.commit()
        return redirect(url_for('main.index'))
    return render_template('question/question_form.html', form=form)

@bp.route('/detail/<int:question_id>/') # 매개변수 URL 매핑 규칙
def detail(question_id):
    form = AnswerForm()
    question = Question.query.get_or_404(question_id) # 매개변수로 전달 받은 id의 질문
    return render_template('question/question_detail.html', question = question, form=form)

한상범/flask_study/pybo/templates/form_errors.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% if form.errors %}
    <div class="alert alert-danger" role="alert">
        {% for field, errors in form.errors.items() %}
        <strong>{{ form[field].label }}</strong>
        <ul>
            {% for error in errors %}
            <li>{{ error }}</li>
            {% endfor %}
        </ul>
        {% endfor %}
    </div>
    {% endif %}
    <!-- flash 오류 -->
    {% for message in get_flashed_messages() %}
    <div class="alert alert-danger" role="alert">
        {{ message }}
    </div>
    {% endfor %}
</body>
</html>

한상범/flask_study/pybo/templates/question/question_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
</head>
<body>
    <!-- 네비게이션바 -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
        <div class="container-fluid">
            <a class="navbar-brand" href="{{ url_for('main.index') }}">Pybo</a>
            <button class="navbar-toggler" type="button"
                    data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent"
                    aria-expanded="false"
                    aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                {% if g.user %}
                <ul class="navbar-nav">
                    <li class="nav-item ">
                        <a class="nav-link" href="{{ url_for('auth.logout') }}">{{ g.user.username }} (로그아웃)</a>
                    </li>
                </ul>
                {% else %}
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.signup') }}">계정생성</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.login') }}">로그인</a>
                    </li>
                </ul>
                {% endif %}
            </div>
        </div>
    </nav>
    <h1>{{ question.subject }}</h1>
    <div>
        {{ question.content }}
    </div>
    <h5>{{ question.answer_set|length }}개의 답변이 있습니다.</h5>
    <div>
        <ul>
        {% for answer in question.answer_set %}
            <li>{{ answer.content }}</li>
        {% endfor %}
        </ul>
    </div>

    <form action="{{ url_for('answer.create', question_id=question.id) }}" method="post">
        {{ form.csrf_token }}
        <textarea name="content" id="content" rows="15"></textarea>
        <input type="submit" value="답변등록">
    </form>

</body>
</html>

한상범/flask_study/pybo/templates/question/question_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <title>Document</title>
</head>
<body>
    <!-- 네비게이션바 -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
        <div class="container-fluid">
            <a class="navbar-brand" href="{{ url_for('main.index') }}">Pybo</a>
            <button class="navbar-toggler" type="button"
                    data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent"
                    aria-expanded="false"
                    aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                {% if g.user %}
                <ul class="navbar-nav">
                    <li class="nav-item ">
                        <a class="nav-link" href="{{ url_for('auth.logout') }}">{{ g.user.username }} (로그아웃)</a>
                    </li>
                </ul>
                {% else %}
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.signup') }}">계정생성</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.login') }}">로그인</a>
                    </li>
                </ul>
                {% endif %}
            </div>
        </div>
    </nav>
    <div class="container">
        <h5 class="my-3 border-bottom pb-2">질문등록</h5>
        <form method="post" class="my-3">
            {{ form.csrf_token }}

            {{ form.subject.label }}
            {{ form.subject() }}
    
            {{ form.content.label }}
            {{ form.content() }}
    
            <button type="submit" class="btn btn-primary">저장하기</button>
        </form>
    </div>
</body>
</html>

한상범/flask_study/pybo/templates/question/question_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
</head>
<body>
    <!-- 네비게이션바 -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
        <div class="container-fluid">
            <a class="navbar-brand" href="{{ url_for('main.index') }}">Pybo</a>
            <button class="navbar-toggler" type="button"
                    data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent"
                    aria-expanded="false"
                    aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                {% if g.user %}
                <ul class="navbar-nav">
                    <li class="nav-item ">
                        <a class="nav-link" href="{{ url_for('auth.logout') }}">{{ g.user.username }} (로그아웃)</a>
                    </li>
                </ul>
                {% else %}
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.signup') }}">계정생성</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.login') }}">로그인</a>
                    </li>
                </ul>
                {% endif %}
            </div>
        </div>
    </nav>
    <!-- render 함수에서 전달받은 질문 목록 데이터가 있는지 검사 -->
    {% if question_list %}
        <ul>

<!--        목록에 저장된 데이터를 하나씩 꺼내 question 객체에 대입한다.-->
        {% for question in question_list %}
            <li><a href="{{ url_for('question.detail', question_id=question.id) }}">{{ question.subject }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>질문이 없습니다.</p>
    {% endif %}

    <a href="{{ url_for('question.create') }}" class="btn btn-primary">질문 등록하기</a>
</body>
</html>