Yuranjang/myproject/mysite/views/auth_views.py
from flask import Blueprint, url_for, render_template, flash, request, session, g
from werkzeug.security import generate_password_hash, check_password_hash
from werkzeug.utils import redirect

from mysite import db
from mysite.forms import UserCreateForm, UserLoginForm
from mysite.models import User

bp = Blueprint('auth', __name__, url_prefix='/auth')


@bp.route('/signup/', methods=('GET', 'POST'))
def signup():
    form = UserCreateForm()
    if request.method == 'POST' and form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if not user:
            user = User(username=form.username.data,
                        password=generate_password_hash(form.password1.data),
                        email=form.email.data)
            db.session.add(user)
            db.session.commit()
            return redirect(url_for('main.hello_world'))
        else:
            flash('이미 존재하는 사용자입니다.')
    return render_template('auth/signup.html', form=form)


@bp.route('/login/', methods=('GET', 'POST'))
def login():
    form = UserLoginForm()
    if request.method == 'POST' and form.validate_on_submit():
        error = None
        user = User.query.filter_by(username=form.username.data).first()
        if not user:
            error = "존재하지 않는 사용자입니다."
        elif not check_password_hash(user.password, form.password.data):
            error = "비밀번호가 올바르지 않습니다."
        if error is None:
            session.clear()
            session['user_id'] = user.id
            return redirect(url_for('main.hello_world'))
        flash(error)
    return render_template('auth/login.html', form=form)


@bp.before_app_request
def load_logged_in_user():
    user_id = session.get('user_id')
    if user_id is None:
        g.user = None
    else:
        g.user = User.query.get(user_id)


@bp.route('/logout/')
def logout():
    session.clear()
    return redirect(url_for('main.hello_world'))

Yuranjang/myproject/mysite/views/dtb_views.py
from flask import render_template, Blueprint, request
import sqlite3
import pandas as pd


bp = Blueprint('dtb', __name__, url_prefix='/dtb')


def get_db(db_name):
    return sqlite3.connect(db_name)


def exe_sql(conn, command: str):
    try:
        conn.execute(command)
        conn.commit()

        if command.split(" ")[0].lower() == 'select':
            df = pd.read_sql(command, conn, index_col=None)
            df_html = df.to_html()
            return df_html, 2
        else:
            return 'select 아님', 1
    except:
        return None, 0


@bp.route('/')
def dtb():
    return render_template('dtb/dtb.html')


@bp.route('/dbsql/', methods=["POST"])
def sql_test():
    if request.method == 'POST':
        db_name = request.form.get('db_name')
        sql_command = request.form.get('sql')

        conn = get_db(db_name)

        output, status = exe_sql(conn, sql_command)
        if status == 1:
            return render_template('dtb/dtb.html', label="정상 작동")
        elif status == 2:
            return render_template('dtb/show_table.html') + output
        else:
            return render_template('dtb/dtb.html', label="오류 발생", output=None)
    else:
        return render_template('dtb/dtb.html')


@bp.route('/show_table',methods=['POST'])
def show_table():
    return render_template('dtb/show_table.html')

Yuranjang/myproject/mysite/views/image_views.py
from flask import Blueprint, url_for, render_template, request
from werkzeug.utils import redirect
from PIL import Image


bp = Blueprint('image', __name__, url_prefix='/image')


def image_resize(img, width, height):
    return img.resize((int(width), int(height)))


def image_rotate(img):
    return img.transpose(Image.ROTATE_180)


def image_change_bw(img):
    return img.convert('L')


@bp.route("/")
def image():
    return render_template('image/image_pro.html')


@bp.route('/image_preprocess/', methods=['POST'])
def preprocessing():
    if request.method == 'POST':
        file = request.files['uploaded_image']
        if not file:
            return render_template('image/image_pro.html', label="No Files")

        img = Image.open(file)

        is_rotate_180 = request.form.get('pre_toggle_0')
        is_change_bw = request.form.get('pre_toggle_1')
        is_change_size = request.form.get('pre_toggle_2')

        img.save(f'mysite/static/{file.filename}')

        if is_rotate_180 == 'on':
            img = image_rotate(img)

        if is_change_bw == 'on':
            img = image_change_bw(img)

        if is_change_size == 'on':
            img = image_resize(img, request.form.get('changed_width'), request.form.get('changed_height'))

        img.save(f'mysite/static/changed_{file.filename}')

        # 결과 리턴
        return render_template('image/image_pro.html', label=file.filename)

Yuranjang/myproject/mysite/views/question_views.py
from datetime import datetime

from flask import Blueprint, render_template, request, url_for
from werkzeug.utils import redirect

from .. import db
from mysite.models import Question

from mysite.forms import QuestionForm

bp = Blueprint('question', __name__, url_prefix='/question')


@bp.route('/list/')
def _list():
    question_list = Question.query.order_by(Question.create_date.desc())
    return render_template('question/question_list.html', question_list=question_list)


@bp.route('/detail/<int:question_id>/')
def detail(question_id):
    question = Question.query.get_or_404(question_id)
    return render_template('question/question_detail.html', question=question)


@bp.route('/create/', methods=('GET','POST'))
def create():
    form = QuestionForm()
    if request.method == 'POST' and form.validate_on_submit():
        question = Question(subject=form.subject.data, content=form.content.data, create_date=datetime.now())
        db.session.add(question)
        db.session.commit()
        return redirect(url_for('main.index'))
    return render_template('question/question_form.html', form=form)

Yuranjang/myproject/mysite/templates/base.html
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap.min.css') }}">
    <!-- mysite CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <title>my_mini_project</title>
</head>
<body>
<!-- 네비게이션바 -->
{% include "navbar.html" %}
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
<!-- Bootstrap JS -->
<script src="{{ url_for('static', filename='bootstrap.min.js') }}"></script>
</body>
</html>

Yuranjang/myproject/mysite/templates/form_errors.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% if form.errors %}
<div class="alert alert-danger" role="alert">
    {% for field, errors in form.errors.items() %}
    <strong>{{ form[field].label }}</strong>
    <ul>
        {% for error in errors %}
        <li>{{ error }}</li>
        {% endfor %}
    </ul>
    {% endfor %}
</div>
{% endif %}
<!-- flash 오류 -->
{% for message in get_flashed_messages() %}
<div class="alert alert-danger" role="alert">
    {{ message }}
</div>
{% endfor %}
</body>
</html>

Yuranjang/myproject/mysite/templates/helloworld.html
{% extends 'base.html' %}
{% block content %}
<h1 class="hlwd">Hello, Flask!</h1>
<br>
<h3 class="hlwd">플라스크 프로젝트 메인 화면입니다.</h3>
<br>
<div class="hlwd">
    <a href="{{url_for('question._list')}}"><button type="button" class="btn btn-outline-primary">게시판</button></a>
    &nbsp;
    <a href="{{url_for('image.image')}}"><button type="button" class="btn btn-outline-primary">이미지처리</button></a>
    &nbsp;
    <a href="{{url_for('dtb.dtb')}}"><button type="button" class="btn btn-outline-primary">SQL처리</button></a>
</div>
{% endblock %}

Yuranjang/myproject/mysite/templates/navbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light border-bottom", style="background-color: #e3f2fd;">
    <div class="container-fluid">
        <a class="navbar-brand" href="{{ url_for('main.hello_world') }}">MySite</a>
        <button class="navbar-toggler" type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            {% if g.user %}
            <ul class="navbar-nav">
                <li class="nav-item ">
                    <a class="nav-link" href="{{ url_for('auth.logout') }}">{{ g.user.username }} (로그아웃)</a>
                </li>
            </ul>
            {% else %}
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.signup') }}">계정생성</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.login') }}">로그인</a>
                </li>
            </ul>
            {% endif %}
        </div>
    </div>
</nav>
</body>
</html>